### ISSUE TITLE
Is there any paper reference for this technique?

### ISSUE THREAD

**Issue by mrgloom** [stephengrice/synth-me#1]
Is there any paper reference for this technique?

**Comment by stephengrice** [comment]
Hi mrgloom,

I did not use a paper to make this project. I figured out how to do it from searching around on Google. My main source was this page: https://www.explainthatstuff.com/how-speech-synthesis-works.html

The author cites a number of articles, technical papers, and books at the bottom.

I also threw together a PowerPoint for when I presented this in school. If I can find it, I'll add it to the repository.

Does that help?
