### ISSUE TITLE
No prompt

### ISSUE THREAD

**Issue by jochemstoel** [stephengrice/synth-me#2]
Hey I have been searching for a working prototype of a concatenative speech synthesis script for ages (possibly years) but none of them work or they produce shit quality. Today I was trying out yours.

When I git clone this repository and run _python synthme.py_ I get this
```bash
Traceback (most recent call last):
  File "synthme.py", line 5, in <module>
    from synthme import tts
  File "C:\Users\norep\Desktop\synth-me\synthme\tts.py", line 10
    debug and print("Text to Speech Generation started.")
                  ^
SyntaxError: invalid syntax
```

When I run _python3 synthme.py_  I get no prompt at all whatsoever and it just exits without any warning or error. I am running Windows 10.

I don't have a lot of experience with Python, what am I doing wrong?

**Comment by stephengrice** [comment]
This is the output I have:
$ python synthme.py
```
Message: hey
Text to Speech Generation started.
Words list: ['hey']
Phonemes list: [24, 3, 25, 48]
File created.
```

What python version are you using? Mine is 3.5.2.

Mine also fails on python 2. I will try to fix that.

**Comment by stephengrice** [comment]
@jochemstoel Please do a `git pull` and try again - I hope this will fix it for you. Also make sure that you do a `python -m pip install -r requirements.txt`, or simply run `pip install future`. Then python2 might start working.

If you're actually interested in / in need of this package, also please let me know. I did it quite a few years ago while I was still in school and didn't think anyone would ever need it. It could definitely use some polishing :)

Thanks!
